	<!-- 禁止浏览器缩放 -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<!-- 清除浏览器缓存 -->
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="Cache-Control" content="no-cache, must-revalidate">
	<meta http-equiv="expires" content="Wed, 26 Feb 1997 08:21:57 GMT">
	<!--屏幕顶部条的颜色-->
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	<!-- 默认值为 default（白色），可以定为 black（黑色）和 black-translucent（灰色半透明）； -->